name: Abbey Grant Kit Materialize

on:
  push:
    branches:
      - main

jobs:
  materialize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - run: bundle install

      - name: Terraspace Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraspace up demo -auto-approve -input=false
        env:
          ABBEY_TOKEN: ${{ secrets.ABBEY_TOKEN }}
          TF_HTTP_USERNAME: starter-kit
          TF_HTTP_PASSWORD: ${{ secrets.ABBEY_TOKEN }}
          TF_VAR_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          TF_VAR_username: ${{ secrets.SNOWFLAKE_USERNAME }}
          TF_VAR_password: ${{ secrets.SNOWFLAKE_PASSWORD }}